### ISSUE TITLE
npm start 出错

### ISSUE THREAD

**Issue by ProdigalExcalibur** [elva2596/vueBlog#14]
JamesMacBookPro:server james$ npm start

> server@1.0.0 start /Volumes/JamesData/vue-workspace/vueBlog/server
> cross-env NODE_ENV=production pm2 start app.js --node-args='--harmony' --name 'server'

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn pm2 ENOENT
    at exports._errnoException (util.js:1012:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:577:11)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3

npm ERR! Darwin 17.3.0
npm ERR! argv "/usr/local/Cellar/node/6.3.1/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! server@1.0.0 start: `cross-env NODE_ENV=production pm2 start app.js --node-args='--harmony' --name 'server'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the server@1.0.0 start script 'cross-env NODE_ENV=production pm2 start app.js --node-args='--harmony' --name 'server''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production pm2 start app.js --node-args='--harmony' --name 'server'
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls server
npm ERR! There is likely additional logging output above.

怎么解决？

**Comment by ProdigalExcalibur** [comment]
npm 版本3.10.3
node 版本v6.3.1
