### ISSUE TITLE
npm install 后报错了

### ISSUE THREAD

**Issue by rudyxu1102** [elva2596/vueBlog#3]
不知道为什么，请教博主

>PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-windows.zip
Saving to C:\Users\fatdong\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip
Receiving...
  [==--------------------------------------] 5%
Error making request.
Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:569:26)

**Comment by rudyxu1102** [comment]
不过还是可以打开blog

**Comment by rudyxu1102** [comment]
> warning  in ./~/NProgress/nprogress.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

    
![image](https://cloud.githubusercontent.com/assets/22772600/23753393/4a8c46a4-0514-11e7-8d2f-57bae5305288.png)
一直显示加载中

**Comment by rudyxu1102** [comment]
>Error
    at Model.ensureIndex (D:\blog\vueBlog\node_modules\mongolass\lib\query.js:108:16)
    at Object.<anonymous> (D:\blog\vueBlog\server\lib\mongo.js:43:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\blog\vueBlog\server\api\index.js:1:98)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

**Comment by rudyxu1102** [comment]
```
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "E:\\软件\\node.js\\node.exe" "E:\\软件\\node.js\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! chromedriver@2.27.3 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chromedriver@2.27.3 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\blog\new\vueBlog\npm-debug.log

```

**Comment by rudyxu1102** [comment]
看ERR信息发现是chromedriver安装出错，
>网上找到的解决方法：
npm install chromedriver --chromedriver_cdnurl=http://cdn.npm.taobao.org/dist/chromedriver

**Comment by elva2596** [comment]
phantom 就是这样国内镜像下载慢，我是切换回npm镜像 然后翻墙安装的。其它问题目测你没启动数据库吧？

**Comment by rudyxu1102** [comment]
可以运行了，谢谢博主
